        # XHTTP → path как в xray Config Profile (streamSettings.xhttpSettings.path)
        location /xhttppath/ {
            client_max_body_size 0;
            client_body_timeout 5m;
            grpc_socket_keepalive on;
            grpc_set_header Host $host;
            grpc_set_header X-Real-IP $remote_addr;
            grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            grpc_set_header X-Forwarded-Proto $scheme;
            grpc_set_header Connection "";
            grpc_pass unix:/dev/shm/xrxh.socket;
        }
